"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    about: "About",
    menu: "Menu",
    gallery: "Gallery",
    reviews: "Reviews",
    contact: "Contact",
    orders: "Orders",
    reservations: "Reservations",
    cart: "Cart",
    wishlist: "Wishlist",
    checkout: "Checkout",
    login: "Login",
    register: "Register",
    logout: "Logout",
    addToCart: "Add to Cart",
    removeFromCart: "Remove",
    clearCart: "Clear Cart",
    proceedToCheckout: "Proceed to Checkout",
    placeOrder: "Place Order",
    orderPlaced: "Order placed successfully!",
    reserveTable: "Reserve a Table",
    confirmReservation: "Confirm Reservation",
    reservationConfirmed: "Reservation confirmed!",
    admin: "Admin",
    qrCode: "QR Code",
    giftCards: "Gift Cards",
    tableOrder: "Table Order",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    price: "Price",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Discount",
    delivery: "Delivery",
    promoCode: "Promo Code",
    apply: "Apply",
    remove: "Remove",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    notes: "Notes",
    guests: "Guests",
    date: "Date",
    time: "Time",
    browseMenu: "Browse Menu",
    continueShopping: "Continue Shopping",
    viewFullCart: "View Full Cart",
    noOrders: "No orders yet",
    noReservations: "No reservations yet",
    loyaltyPoints: "Loyalty Points",
    orderHistory: "Order History",
    reorder: "Reorder",
    clearHistory: "Clear History",
    printMenu: "Print Menu",
    downloadQR: "Download QR Code",
    createGiftCard: "Create Gift Card",
    redeemGiftCard: "Redeem Gift Card",
    amount: "Amount",
    balance: "Balance",
    invalidCode: "Invalid gift card code",
    status: "Status",
    pending: "Pending",
    preparing: "Preparing",
    ready: "Ready",
    completed: "Completed",
    cancelled: "Cancelled",
    viewDetails: "View Details",
    customer: "Customer",
    items: "Items",
    thankYou: "Thank you for your order!",
    welcomeBack: "Welcome Back",
    signIn: "Sign In",
    createAccount: "Create Account",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    fullName: "Full Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot password?",
    rememberMe: "Remember me",
    signInWithGoogle: "Sign in with Google",
    or: "or",
    and: "and",
    orContinueWith: "Or continue with",
    agreeToTerms: "I agree to the terms and conditions",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    allRightsReserved: "All rights reserved",
    madeWith: "Made with",
    by: "by",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    reset: "Reset",
    clear: "Clear",
    searchPlaceholder: "Search...",
    noResults: "No results found",
    showingResults: "Showing results",
    of: "of",
    results: "results",
    itemsPerPage: "Items per page",
    page: "Page",
    ofTotal: "of",
    firstPage: "First",
    lastPage: "Last",
    goToPage: "Go to page",
    filterBy: "Filter by",
    sortBy: "Sort by",
    newestFirst: "Newest first",
    oldestFirst: "Oldest first",
    priceLowToHigh: "Price: Low to High",
    priceHighToLow: "Price: High to Low",
    nameAToZ: "Name: A to Z",
    nameZToA: "Name: Z to A",
    category: "Category",
    allCategories: "All Categories",
    featured: "Featured",
    onSale: "On Sale",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    addToWishlist: "Add to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    share: "Share",
    copyLink: "Copy Link",
    linkCopied: "Link copied to clipboard",
    shareOnWhatsApp: "Share on WhatsApp",
    shareOnX: "Share on X",
    writeReview: "Write a Review",
    submitReview: "Submit Review",
    reviewSubmitted: "Review submitted!",
    rating: "Rating",
    comment: "Comment",
    yourReview: "Your Review",
    reviewsCount: "reviews",
    averageRating: "Average Rating",
    recommended: "Recommended",
    youMayAlsoLike: "You may also like",
    recentlyViewed: "Recently Viewed",
    clearRecentlyViewed: "Clear Recently Viewed",
    cookieConsent: "We use cookies to improve your experience.",
    acceptCookies: "Accept",
    declineCookies: "Decline",
    backToTop: "Back to top",
    scrollToTop: "Scroll to top",
    pageNotFound: "Page not found",
    goBackHome: "Go back home",
    internalServerError: "Internal server error",
    tryAgainLater: "Please try again later",
    maintenanceMode: "Site under maintenance",
    comingSoon: "Coming soon",
    newsletter: "Newsletter",
    subscribe: "Subscribe",
    unsubscribe: "Unsubscribe",
    emailPlaceholder: "Enter your email",
    thankYouForSubscribing: "Thank you for subscribing!",
    contactUs: "Contact Us",
    sendMessage: "Send Message",
    messageSent: "Message sent!",
    message: "Message",
    subject: "Subject",
    phoneNumber: "Phone Number",
    findUs: "Find Us",
    openingHours: "Opening Hours",
    followUs: "Follow Us",
    facebook: "Facebook",
    twitter: "Twitter",
    youtube: "YouTube",
    tiktok: "TikTok",
    snapchat: "Snapchat",
    linkedin: "LinkedIn",
    pinterest: "Pinterest",
    telegram: "Telegram",
    wechat: "WeChat",
    line: "Line",
    viber: "Viber",
    phoneCall: "Phone Call",
    emailUs: "Email Us",
    getDirections: "Get Directions",
    viewOnMap: "View on map",
    location: "Location",
    city: "City",
    country: "Country",
    postalCode: "Postal Code",
    state: "State",
    currency: "Currency",
    qar: "QAR",
    usd: "USD",
    eur: "EUR",
    gbp: "GBP",
    sar: "SAR",
    aed: "AED",
    egp: "EGP",
    jod: "JOD",
    lbp: "LBP",
    iqd: "IQD",
    kwd: "KWD",
    omr: "OMR",
    qatariRial: "Qatari Rial",
    usDollar: "US Dollar",
    euro: "Euro",
    britishPound: "British Pound",
    saudiRiyal: "Saudi Riyal",
    uaeDirham: "UAE Dirham",
    egyptianPound: "Egyptian Pound",
    jordanianDinar: "Jordanian Dinar",
    lebanesePound: "Lebanese Pound",
    iraqiDinar: "Iraqi Dinar",
    kuwaitiDinar: "Kuwaiti Dinar",
    omaniRial: "Omani Rial",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    toggleTheme: "Toggle theme",
    menuIsEmpty: "Menu is empty",
    addItemsFromMenu: "Add items from our menu to get started",
    yourCartIsEmpty: "Your cart is empty",
    yourWishlistIsEmpty: "Your wishlist is empty",
    savedForLater: "Saved for Later",
    moveToCart: "Move to Cart",
    itemAddedToCart: "Item added to cart",
    itemRemovedFromCart: "Item removed from cart",
    itemAddedToWishlist: "Item added to wishlist",
    itemRemovedFromWishlist: "Item removed from wishlist",
    quantityUpdated: "Quantity updated",
    cartUpdated: "Cart updated",
    wishlistUpdated: "Wishlist updated",
    orderConfirmed: "Order confirmed",
    reservationCreated: "Reservation created",
    promoApplied: "Promo applied",
    promoRemoved: "Promo removed",
    invalidPromo: "Invalid promo code",
    giftCardCreated: "Gift card created",
    giftCardRedeemed: "Gift card redeemed",
    pointsEarned: "points earned",
    thankYouForYourOrder: "Thank you for your order!",
    yourOrderNumber: "Your order number",
    hasBeenPlacedSuccessfully: "has been placed successfully",
    browseOurMenu: "Browse our menu",
    orderNow: "Order Now",
    bookNow: "Book Now",
    learnMore: "Learn More",
    readMore: "Read More",
    showLess: "Show Less",
    viewAll: "View All",
    seeAll: "See All",
    loadMore: "Load More",
    showMore: "Show More",
    expand: "Expand",
    collapse: "Collapse",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    openCart: "Open cart",
    closeCart: "Close cart",
    openSearch: "Open search",
    closeSearch: "Close search",
    searchResults: "Search results",
    noSearchResults: "No search results",
    searchFor: "Search for",
    trending: "Trending",
    popular: "Popular",
    new: "New",
    bestSeller: "Best Seller",
    limitedTime: "Limited Time",
    exclusive: "Exclusive",
    specialOffer: "Special Offer",
    freeDelivery: "Free Delivery",
    buyOneGetOne: "Buy One Get One",
    sale: "Sale",
    nutrition: "Nutrition",
    allergens: "Allergens",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    sugar: "Sugar",
    fiber: "Fiber",
    contains: "Contains",
    mayContain: "May Contain",
    photoReviews: "Photo Reviews",
    uploadPhoto: "Upload Photo",
    corporate: "Corporate",
    bulkOrder: "Bulk Order",
    bot: "Bot",
    chat: "Chat",
    digitalMenu: "Digital Menu",
    menuBoard: "Menu Board",
    tableQR: "Table QR",
    notifications: "Notifications",
    push: "Push",
    sms: "SMS",
    autoPost: "Auto Post",
    giftCardMailing: "Gift Card Mailing",
    birthdayReward: "Birthday Reward",
    seasonalCountdown: "Seasonal Countdown",
    daysLeft: "Days Left",
    hoursLeft: "Hours Left",
    minutesLeft: "Minutes Left",
    secondsLeft: "Seconds Left",
    ramadan: "Ramadan",
    eid: "Eid",
    rateLimit: "Rate Limit",
    customization: "Customization",
    buildYourOwn: "Build Your Own",
    extras: "Extras",
    refine: "Refine",
    resetFilters: "Reset Filters",
    applyFilters: "Apply Filters",
    filters: "Filters",
    categories: "Categories",
    priceRange: "Price Range",
    min: "Min",
    max: "Max",
    go: "Go",
    showing: "Showing",
    to: "to",
    totalResults: "total results",
    noItemsFound: "No items found",
    tryAdjustingFilters: "Try adjusting your filters",
    clearAllFilters: "Clear all filters",
    activeFilters: "Active filters",
    filterByPrice: "Filter by price",
    filterByCategory: "Filter by category",
    filterByRating: "Filter by rating",
    filterByAvailability: "Filter by availability",
    inStockOnly: "In stock only",
    outOfStockOnly: "Out of stock only",
    ratingAndUp: "Rating and up",
    anyRating: "Any rating",
    fiveStars: "5 stars",
    fourStarsAndUp: "4 stars and up",
    threeStarsAndUp: "3 stars and up",
    twoStarsAndUp: "2 stars and up",
    oneStarAndUp: "1 star and up",
    sortByFeatured: "Sort by featured",
    sortByNewest: "Sort by newest",
    sortByPrice: "Sort by price",
    sortByRating: "Sort by rating",
    sortByPopularity: "Sort by popularity",
    featuredFirst: "Featured first",
    priceAscending: "Price: Low to High",
    priceDescending: "Price: High to Low",
    ratingDescending: "Rating: High to Low",
    popularityDescending: "Popularity",
    nameAscending: "Name: A to Z",
    nameDescending: "Name: Z to A",
    relevance: "Relevance",
    defaultSort: "Default",

  },
  ar: {
    home: "الرئيسية",
    about: "من نحن",
    menu: "القائمة",
    gallery: "المعرض",
    reviews: "التقييمات",
    contact: "اتصل بنا",
    orders: "الطلبات",
    reservations: "الحجوزات",
    cart: "السلة",
    wishlist: "قائمة الأمنيات",
    checkout: "الدفع",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    addToCart: "أضف للسلة",
    removeFromCart: "إزالة",
    clearCart: "تفريغ السلة",
    proceedToCheckout: "متابعة الدفع",
    placeOrder: "تأكيد الطلب",
    orderPlaced: "تم وضع الطلب بنجاح!",
    reserveTable: "حجز طاولة",
    confirmReservation: "تأكيد الحجز",
    reservationConfirmed: "تم تأكيد الحجز!",
    admin: "لوحة التحكم",
    qrCode: "رمز QR",
    giftCards: "بطاقات هدايا",
    tableOrder: "طلب طاولة",
    search: "بحث",
    filter: "تصفية",
    sort: "ترتيب",
    price: "السعر",
    total: "المجموع",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    delivery: "التوصيل",
    promoCode: "كود الخصم",
    apply: "تطبيق",
    remove: "إزالة",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    address: "العنوان",
    notes: "ملاحظات",
    guests: "ضيوف",
    date: "التاريخ",
    time: "الوقت",
    browseMenu: "تصفح القائمة",
    continueShopping: "متابعة التسوق",
    viewFullCart: "عرض السلة",
    noOrders: "لا توجد طلبات بعد",
    noReservations: "لا توجد حجوزات بعد",
    loyaltyPoints: "نقاط الولاء",
    orderHistory: "سجل الطلبات",
    reorder: "إعادة الطلب",
    clearHistory: "مسح السجل",
    printMenu: "طباعة القائمة",
    downloadQR: "تنزيل رمز QR",
    createGiftCard: "إنشاء بطاقة هدية",
    redeemGiftCard: "استبدال بطاقة هدية",
    amount: "المبلغ",
    balance: "الرصيد",
    invalidCode: "كود بطاقة الهدية غير صالح",
    status: "الحالة",
    pending: "قيد الانتظار",
    viewDetails: "عرض التفاصيل",
    customer: "العميل",
    items: "العناصر",
    thankYou: "شكراً لطلبك!",
    welcomeBack: "مرحباً بعودتك",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    fullName: "الاسم الكامل",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    rememberMe: "تذكرني",
    signInWithGoogle: "تسجيل الدخول بجوجل",
    or: "أو",
    and: "و",
    orContinueWith: "أو تابع باستخدام",
    agreeToTerms: "أوافق على الشروط والأحكام",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    allRightsReserved: "جميع الحقوق محفوظة",
    madeWith: "صنع بـ",
    by: "بواسطة",
    loading: "جاري التحميل...",
    error: "خطأ",
    success: "نجاح",
    warning: "تحذير",
    info: "معلومات",
    close: "إغلاق",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    submit: "إرسال",
    reset: "إعادة تعيين",
    clear: "مسح",
    searchPlaceholder: "بحث...",
    noResults: "لا توجد نتائج",
    showingResults: "عرض النتائج",
    of: "من",
    results: "نتائج",
    itemsPerPage: "عناصر لكل صفحة",
    page: "الصفحة",
    ofTotal: "من",
    firstPage: "الأولى",
    lastPage: "الأخيرة",
    goToPage: "اذهب إلى الصفحة",
    filterBy: "تصفية حسب",
    sortBy: "ترتيب حسب",
    newestFirst: "الأحدث أولاً",
    oldestFirst: "الأقدم أولاً",
    priceLowToHigh: "السعر: من الأقل للأعلى",
    priceHighToLow: "السعر: من الأعلى للأقل",
    nameAToZ: "الاسم: من أ إلى ي",
    nameZToA: "الاسم: من ي إلى أ",
    category: "الفئة",
    allCategories: "جميع الفئات",
    featured: "مميز",
    onSale: "عرض",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    addToWishlist: "أضف لقائمة الأمنيات",
    removeFromWishlist: "إزالة من قائمة الأمنيات",
    share: "مشاركة",
    copyLink: "نسخ الرابط",
    linkCopied: "تم نسخ الرابط",
    shareOnWhatsApp: "مشاركة عبر واتساب",
    shareOnX: "مشاركة على X",
    writeReview: "اكتب تقييماً",
    submitReview: "إرسال التقييم",
    reviewSubmitted: "تم إرسال التقييم!",
    rating: "التقييم",
    comment: "التعليق",
    yourReview: "تقييمك",
    reviewsCount: "تقييمات",
    averageRating: "متوسط التقييم",
    recommended: "موصى به",
    youMayAlsoLike: "قد يعجبك أيضاً",
    recentlyViewed: "تمت مشاهدته مؤخراً",
    clearRecentlyViewed: "مسح السجل",
    cookieConsent: "نستخدم ملفات تعريف الارتباط لتحسين تجربتك.",
    acceptCookies: "قبول",
    declineCookies: "رفض",
    backToTop: "العودة للأعلى",
    scrollToTop: "التمرير للأعلى",
    pageNotFound: "الصفحة غير موجودة",
    goBackHome: "العودة للرئيسية",
    internalServerError: "خطأ في الخادم",
    tryAgainLater: "يرجى المحاولة مرة أخرى لاحقاً",
    maintenanceMode: "الموقع تحت الصيانة",
    comingSoon: "قريباً",
    newsletter: "النشرة الإخبارية",
    subscribe: "اشترك",
    unsubscribe: "إلغاء الاشتراك",
    emailPlaceholder: "أدخل بريدك الإلكتروني",
    thankYouForSubscribing: "شكراً لاشتراكك!",
    contactUs: "اتصل بنا",
    sendMessage: "إرسال الرسالة",
    messageSent: "تم إرسال الرسالة!",
    message: "الرسالة",
    subject: "الموضوع",
    phoneNumber: "رقم الهاتف",
    findUs: "موقعنا",
    openingHours: "ساعات العمل",
    followUs: "تابعنا",
    facebook: "فيسبوك",
    twitter: "تويتر",
    youtube: "يوتيوب",
    tiktok: "تيك توك",
    snapchat: "سناب شات",
    linkedin: "لينكد إن",
    pinterest: "بينترست",
    telegram: "تيليجرام",
    wechat: "وي تشات",
    line: "لاين",
    viber: "فايبر",
    phoneCall: "اتصال",
    emailUs: "راسلنا",
    getDirections: "احصل على الاتجاهات",
    viewOnMap: "عرض على الخريطة",
    location: "الموقع",
    city: "المدينة",
    country: "الدولة",
    postalCode: "الرمز البريدي",
    state: "المنطقة",
    currency: "العملة",
    qar: "ريال قطري",
    usd: "دولار أمريكي",
    eur: "يورو",
    gbp: "جنيه إسترليني",
    sar: "ريال سعودي",
    aed: "درهم إماراتي",
    egp: "جنيه مصري",
    jod: "دينار أردني",
    lbp: "ليرة لبنانية",
    iqd: "دينار عراقي",
    kwd: "دينار كويتي",
    omr: "ريال عماني",
    qatariRial: "ريال قطري",
    usDollar: "دولار أمريكي",
    euro: "يورو",
    britishPound: "جنيه إسترليني",
    saudiRiyal: "ريال سعودي",
    uaeDirham: "درهم إماراتي",
    egyptianPound: "جنيه مصري",
    jordanianDinar: "دينار أردني",
    lebanesePound: "ليرة لبنانية",
    iraqiDinar: "دينار عراقي",
    kuwaitiDinar: "دينار كويتي",
    omaniRial: "ريال عماني",
    darkMode: "الوضع الداكن",
    lightMode: "الوضع الفاتح",
    toggleTheme: "تبديل المظهر",
    menuIsEmpty: "القائمة فارغة",
    addItemsFromMenu: "أضف عناصر من قائمتنا للبدء",
    yourCartIsEmpty: "سلتك فارغة",
    yourWishlistIsEmpty: "قائمة أمنياتك فارغة",
    savedForLater: "محفوظة لاحقاً",
    moveToCart: "انقل للسلة",
    itemAddedToCart: "تم إضافة العنصر للسلة",
    itemRemovedFromCart: "تم إزالة العنصر من السلة",
    itemAddedToWishlist: "تم إضافة العنصر لقائمة الأمنيات",
    itemRemovedFromWishlist: "تم إزالة العنصر من قائمة الأمنيات",
    quantityUpdated: "تم تحديث الكمية",
    cartUpdated: "تم تحديث السلة",
    wishlistUpdated: "تم تحديث قائمة الأمنيات",
    orderConfirmed: "تم تأكيد الطلب",
    reservationCreated: "تم إنشاء الحجز",
    promoApplied: "تم تطبيق الخصم",
    promoRemoved: "تم إزالة الخصم",
    invalidPromo: "كود خصم غير صالح",
    giftCardCreated: "تم إنشاء بطاقة الهدية",
    giftCardRedeemed: "تم استبدال بطاقة الهدية",
    pointsEarned: "نقاط مكتسبة",
    thankYouForYourOrder: "شكراً لطلبك!",
    yourOrderNumber: "رقم طلبك",
    hasBeenPlacedSuccessfully: "تم وضعه بنجاح",
    browseOurMenu: "تصفح قائمتنا",
    orderNow: "اطلب الآن",
    bookNow: "احجز الآن",
    learnMore: "اعرف المزيد",
    readMore: "اقرأ المزيد",
    showLess: "عرض أقل",
    viewAll: "عرض الكل",
    seeAll: "عرض الكل",
    loadMore: "تحميل المزيد",
    showMore: "عرض المزيد",
    expand: "توسيع",
    collapse: "طي",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    openCart: "فتح السلة",
    closeCart: "إغلاق السلة",
    openSearch: "فتح البحث",
    closeSearch: "إغلاق البحث",
    searchResults: "نتائج البحث",
    noSearchResults: "لا توجد نتائج بحث",
    searchFor: "بحث عن",
    trending: "الأكثر رواجاً",
    popular: "الأشهر",
    new: "جديد",
    bestSeller: "الأكثر مبيعاً",
    limitedTime: "لفترة محدودة",
    exclusive: "حصري",
    specialOffer: "عرض خاص",
    freeDelivery: "توصيل مجاني",
    buyOneGetOne: "اشترِ واحداً واحصل على واحد",
    sale: "تخفيضات",
    nutrition: "التغذية",
    allergens: "مسببات الحساسية",
    calories: "السعرات الحرارية",
    protein: "البروتين",
    carbs: "الكربوهيدرات",
    fat: "الدهون",
    sugar: "السكر",
    fiber: "الألياف",
    contains: "يحتوي على",
    mayContain: "قد يحتوي على",
    photoReviews: "تقييمات بالصور",
    uploadPhoto: "رفع صورة",
    corporate: "شركات",
    bulkOrder: "طلب جماعي",
    bot: "بوت",
    chat: "محادثة",
    digitalMenu: "القائمة الرقمية",
    menuBoard: "لوحة القائمة",
    tableQR: "رمز QR للطاولة",
    notifications: "الإشعارات",
    push: "دفع",
    sms: "رسائل نصية",
    autoPost: "نشر تلقائي",
    giftCardMailing: "إرسال بطاقات الهدايا",
    birthdayReward: "مكافأة عيد الميلاد",
    seasonalCountdown: "عد تنازلي موسمي",
    daysLeft: "أيام متبقية",
    hoursLeft: "ساعات متبقية",
    minutesLeft: "دقائق متبقية",
    secondsLeft: "ثواني متبقية",
    ramadan: "رمضان",
    eid: "العيد",
    rateLimit: "حد المعدل",
    customization: "تخصيص",
    buildYourOwn: "ابنِ طلبك",
    extras: "إضافات",
    refine: "تحسين",
    resetFilters: "إعادة تعيين الفلاتر",
    applyFilters: "تطبيق الفلاتر",
    filters: "الفلاتر",
    categories: "الفئات",
    priceRange: "نطاق السعر",
    min: "الحد الأدنى",
    max: "الحد الأقصى",
    go: "بحث",
    showing: "عرض",
    to: "إلى",
    totalResults: "إجمالي النتائج",
    noItemsFound: "لم يتم العثور على عناصر",
    tryAdjustingFilters: "حاول تعديل الفلاتر",
    clearAllFilters: "مسح جميع الفلاتر",
    activeFilters: "الفلاتر النشطة",
    filterByPrice: "تصفية حسب السعر",
    filterByCategory: "تصفية حسب الفئة",
    filterByRating: "تصفية حسب التقييم",
    filterByAvailability: "تصفية حسب التوفر",
    inStockOnly: "المتوفر فقط",
    outOfStockOnly: "غير المتوفر فقط",
    ratingAndUp: "التقييم وما فوق",
    anyRating: "أي تقييم",
    fiveStars: "5 نجوم",
    fourStarsAndUp: "4 نجوم فأكثر",
    threeStarsAndUp: "3 نجوم فأكثر",
    twoStarsAndUp: "نجمتان فأكثر",
    oneStarAndUp: "نجمة فأكثر",
    sortByFeatured: "ترتيب حسب المميز",
    sortByNewest: "ترتيب حسب الأحدث",
    sortByPrice: "ترتيب حسب السعر",
    sortByRating: "ترتيب حسب التقييم",
    sortByPopularity: "ترتيب حسب الشعبية",
    featuredFirst: "المميز أولاً",
    priceAscending: "السعر: من الأقل للأعلى",
    priceDescending: "السعر: من الأعلى للأقل",
    ratingDescending: "التقييم: من الأعلى للأقل",
    popularityDescending: "الشعبية",
    nameAscending: "الاسم: من أ إلى ي",
    nameDescending: "الاسم: من ي إلى أ",
    relevance: "الصلة",
    defaultSort: "الافتراضي",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language | null;
    if (saved && (saved === "en" || saved === "ar")) {
      setLanguage(saved);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}

