"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    about: "About",
    menu: "Menu",
    gallery: "Gallery",
    reviews: "Reviews",
    contact: "Contact",
    orders: "Orders",
    reservations: "Reservations",
    cart: "Cart",
    wishlist: "Wishlist",
    checkout: "Checkout",
    login: "Login",
    register: "Register",
    logout: "Logout",
    addToCart: "Add to Cart",
    removeFromCart: "Remove",
    clearCart: "Clear Cart",
    proceedToCheckout: "Proceed to Checkout",
    placeOrder: "Place Order",
    orderPlaced: "Order placed successfully!",
    reserveTable: "Reserve a Table",
    confirmReservation: "Confirm Reservation",
    reservationConfirmed: "Reservation confirmed!",
    admin: "Admin",
    qrCode: "QR Code",
    giftCards: "Gift Cards",
    tableOrder: "Table Order",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    price: "Price",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Discount",
    delivery: "Delivery",
    promoCode: "Promo Code",
    apply: "Apply",
    remove: "Remove",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    notes: "Notes",
    specialInstructions: "Special Instructions",
    guests: "Guests",
    date: "Date",
    time: "Time",
    browseMenu: "Browse Menu",
    continueShopping: "Continue Shopping",
    viewFullCart: "View Full Cart",
    noOrders: "No orders yet",
    noReservations: "No reservations yet",
    loyaltyPoints: "Loyalty Points",
    orderHistory: "Order History",
    reorder: "Reorder",
    clearHistory: "Clear History",
    printMenu: "Print Menu",
    downloadQR: "Download QR Code",
    createGiftCard: "Create Gift Card",
    redeemGiftCard: "Redeem Gift Card",
    amount: "Amount",
    balance: "Balance",
    invalidCode: "Invalid gift card code",
    status: "Status",
    pending: "Pending",
    preparing: "Preparing",
    ready: "Ready",
    completed: "Completed",
    cancelled: "Cancelled",
    viewDetails: "View Details",
    customer: "Customer",
    items: "Items",
    thankYou: "Thank you for your order!",
    welcomeBack: "Welcome Back",
    signIn: "Sign In",
    createAccount: "Create Account",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    fullName: "Full Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot password?",
    rememberMe: "Remember me",
    signInWithGoogle: "Sign in with Google",
    or: "or",
    and: "and",
    orContinueWith: "Or continue with",
    agreeToTerms: "I agree to the terms and conditions",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    allRightsReserved: "All rights reserved",
    madeWith: "Made with",
    by: "by",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    reset: "Reset",
    clear: "Clear",
    searchPlaceholder: "Search...",
    noResults: "No results found",
    showingResults: "Showing results",
    of: "of",
    results: "results",
    itemsPerPage: "Items per page",
    page: "Page",
    ofTotal: "of",
    firstPage: "First",
    lastPage: "Last",
    goToPage: "Go to page",
    filterBy: "Filter by",
    sortBy: "Sort by",
    newestFirst: "Newest first",
    oldestFirst: "Oldest first",
    priceLowToHigh: "Price: Low to High",
    priceHighToLow: "Price: High to Low",
    nameAToZ: "Name: A to Z",
    nameZToA: "Name: Z to A",
    category: "Category",
    allCategories: "All Categories",
    featured: "Featured",
    onSale: "On Sale",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    addToWishlist: "Add to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    share: "Share",
    copyLink: "Copy Link",
    linkCopied: "Link copied to clipboard",
    shareOnWhatsApp: "Share on WhatsApp",
    shareOnX: "Share on X",
    writeReview: "Write a Review",
    submitReview: "Submit Review",
    reviewSubmitted: "Review submitted!",
    rating: "Rating",
    comment: "Comment",
    yourReview: "Your Review",
    reviewsCount: "reviews",
    averageRating: "Average Rating",
    recommended: "Recommended",
    youMayAlsoLike: "You may also like",
    recentlyViewed: "Recently Viewed",
    clearRecentlyViewed: "Clear Recently Viewed",
    cookieConsent: "We use cookies to improve your experience.",
    acceptCookies: "Accept",
    declineCookies: "Decline",
    backToTop: "Back to top",
    scrollToTop: "Scroll to top",
    pageNotFound: "Page not found",
    goBackHome: "Go back home",
    internalServerError: "Internal server error",
    tryAgainLater: "Please try again later",
    maintenanceMode: "Site under maintenance",
    comingSoon: "Coming soon",
    newsletter: "Newsletter",
    subscribe: "Subscribe",
    unsubscribe: "Unsubscribe",
    emailPlaceholder: "Enter your email",
    thankYouForSubscribing: "Thank you for subscribing!",
    contactUs: "Contact Us",
    sendMessage: "Send Message",
    messageSent: "Message sent!",
    message: "Message",
    subject: "Subject",
    phoneNumber: "Phone Number",
    findUs: "Find Us",
    openingHours: "Opening Hours",
    followUs: "Follow Us",
    instagram: "Instagram",
    facebook: "Facebook",
    twitter: "Twitter",
    youtube: "YouTube",
    tiktok: "TikTok",
    snapchat: "Snapchat",
    linkedin: "LinkedIn",
    pinterest: "Pinterest",
    whatsapp: "WhatsApp",
    telegram: "Telegram",
    wechat: "WeChat",
    line: "Line",
    viber: "Viber",
    phoneCall: "Phone Call",
    emailUs: "Email Us",
    getDirections: "Get Directions",
    viewOnMap: "View on map",
    location: "Location",
    city: "City",
    country: "Country",
    postalCode: "Postal Code",
    state: "State",
    currency: "Currency",
    qar: "QAR",
    usd: "USD",
    eur: "EUR",
    gbp: "GBP",
    sar: "SAR",
    aed: "AED",
    egp: "EGP",
    jod: "JOD",
    lbp: "LBP",
    iqd: "IQD",
    kwd: "KWD",
    omr: "OMR",
    qatariRial: "Qatari Rial",
    usDollar: "US Dollar",
    euro: "Euro",
    britishPound: "British Pound",
    saudiRiyal: "Saudi Riyal",
    uaeDirham: "UAE Dirham",
    egyptianPound: "Egyptian Pound",
    jordanianDinar: "Jordanian Dinar",
    lebanesePound: "Lebanese Pound",
    iraqiDinar: "Iraqi Dinar",
    kuwaitiDinar: "Kuwaiti Dinar",
    omaniRial: "Omani Rial",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    toggleTheme: "Toggle theme",
    menuIsEmpty: "Menu is empty",
    addItemsFromMenu: "Add items from our menu to get started",
    yourCartIsEmpty: "Your cart is empty",
    yourWishlistIsEmpty: "Your wishlist is empty",
    savedForLater: "Saved for Later",
    moveToCart: "Move to Cart",
    itemAddedToCart: "Item added to cart",
    itemRemovedFromCart: "Item removed from cart",
    itemAddedToWishlist: "Item added to wishlist",
    itemRemovedFromWishlist: "Item removed from wishlist",
    quantityUpdated: "Quantity updated",
    cartUpdated: "Cart updated",
    wishlistUpdated: "Wishlist updated",
    orderConfirmed: "Order confirmed",
    reservationCreated: "Reservation created",
    promoApplied: "Promo applied",
    promoRemoved: "Promo removed",
    invalidPromo: "Invalid promo code",
    giftCardCreated: "Gift card created",
    giftCardRedeemed: "Gift card redeemed",
    pointsEarned: "points earned",
    thankYouForYourOrder: "Thank you for your order!",
    yourOrderNumber: "Your order number",
    hasBeenPlacedSuccessfully: "has been placed successfully",
    browseOurMenu: "Browse our menu",
    orderNow: "Order Now",
    bookNow: "Book Now",
    learnMore: "Learn More",
    readMore: "Read More",
    showLess: "Show Less",
    viewAll: "View All",
    seeAll: "See All",
    loadMore: "Load More",
    showMore: "Show More",
    expand: "Expand",
    collapse: "Collapse",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    openCart: "Open cart",
    closeCart: "Close cart",
    openSearch: "Open search",
    closeSearch: "Close search",
    searchResults: "Search results",
    noSearchResults: "No search results",
    searchFor: "Search for",
    trending: "Trending",
    popular: "Popular",
    new: "New",
    bestSeller: "Best Seller",
    limitedTime: "Limited Time",
    exclusive: "Exclusive",
    specialOffer: "Special Offer",
    freeDelivery: "Free Delivery",
    buyOneGetOne: "Buy One Get One",
    sale: "Sale",
    refine: "Refine",
    resetFilters: "Reset Filters",
    applyFilters: "Apply Filters",
    filters: "Filters",
    categories: "Categories",
    priceRange: "Price Range",
    min: "Min",
    max: "Max",
    go: "Go",
    showing: "Showing",
    to: "to",
    totalResults: "total results",
    noItemsFound: "No items found",
    tryAdjustingFilters: "Try adjusting your filters",
    clearAllFilters: "Clear all filters",
    activeFilters: "Active filters",
    filterByPrice: "Filter by price",
    filterByCategory: "Filter by category",
    filterByRating: "Filter by rating",
    filterByAvailability: "Filter by availability",
    inStockOnly: "In stock only",
    outOfStockOnly: "Out of stock only",
    ratingAndUp: "Rating and up",
    anyRating: "Any rating",
    fiveStars: "5 stars",
    fourStarsAndUp: "4 stars and up",
    threeStarsAndUp: "3 stars and up",
    twoStarsAndUp: "2 stars and up",
    oneStarAndUp: "1 star and up",
    sortByFeatured: "Sort by featured",
    sortByNewest: "Sort by newest",
    sortByPrice: "Sort by price",
    sortByRating: "Sort by rating",
    sortByPopularity: "Sort by popularity",
    featuredFirst: "Featured first",
    priceAscending: "Price: Low to High",
    priceDescending: "Price: High to Low",
    ratingDescending: "Rating: High to Low",
    popularityDescending: "Popularity",
    nameAscending: "Name: A to Z",
    nameDescending: "Name: Z to A",
    relevance: "Relevance",
    defaultSort: "Default",

  },
  ar: {
    trackOrder: "تتبع الطلب",
    orderStatus: "حالة الطلب",
    orderReceived: "تم استلام الطلب",
    confirmed: "تم التأكيد",
    preparing: "جاري التحضير",
    ready: "جاهز",
    outForDelivery: "خارج للتوصيل",
    delivered: "تم التوصيل",
    scanToOrder: "امسح للطلب",
    addTable: "إضافة طاولة",
    tableNumber: "رقم الطاولة",
    seats: "مقاعد",
    label: "التسمية",
    printQR: "طباعة QR",
    downloadQRCode: "تنزيل رمز QR",
    points: "نقاط",
    pointsWorth: "قيمة النقاط",
    totalOrders: "إجمالي الطلبات",
    totalSpent: "إجمالي الإنفاق",
    earnPoints: "اكسب نقطة واحدة مقابل كل ريال قطري تنفقه",
    redeemPoints: "استبدال النقاط",
    lowStock: "مخزون منخفض",
    outOfStock: "نفد المخزون",
    stockRemaining: "متبقي في المخزون",
    inventoryAlert: "تنبيه المخزون",
    orderViaWhatsApp: "اطلب عبر واتساب",
    whatsappOrder: "طلب واتساب",
    loyalty: "نقاط الولاء",
    tracking: "تتبع",
    tablesQR: "رموز QR للطاولات",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language | null;
    if (saved && (saved === "en" || saved === "ar")) {
      setLanguage(saved);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}

